global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'ApiGatewayLR'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Api-gateway service'

  - job_name: 'BookingService'
    metrics_path: '/api/v1/booking/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'Booking service'

  - job_name: 'CarInventoryService'
    metrics_path: '/api/v1/car/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'Car inventory service'

  - job_name: 'CustomerService'
    metrics_path: '/api/v1/customer/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: 'Customer service'

  - job_name: 'PaymentService'
    metrics_path: '/api/v1/payment/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'Payment service'